config/routes.rb
Rails.application.routes.draw do

  resources :boards, except: [:index, :new, :create, :edit]

  resources :cards, except: [:show, :new, :edit]

  root 'boards#show', id: 1
end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :cards, dependent: :destroy

  serialize :card_order
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :board
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params) && \
      @board.update(card_order: params[:card_order])
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit({:card_order => []})
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    cards = Card.where(board_id: params[:board_id]).order(:id)

    section = params[:section_id].to_i
    @cards = \
    Board.find(params[:board_id]).card_order[section].map do |id|
      # http://stackoverflow.com/questions/23221965/ruby-2-0-0-arraybsearch-behavior
      cards.bsearch { |card| id - card.id }
    end

    # @cards = Board.find(params[:board_id]).card_order.map do |arry|
    #   arry.map! do |el|
    #     Card.find(el)
    #   end

    #   return arry
    # end
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @board = Board.find(params[:board_id])
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        @board.card_order[params[:section].to_i].unshift(@card.id)
        @board.save

        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @board = Board.find(params[:board_id])
    @board.card_order[params[:section_id].to_i].delete(@card.id)
    @board.save

    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:title, :board_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/boards/show.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Kanban</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div id="kanban" class="container-fluid">
  <div id="main-region" class="row"></div>
</div>

<div id="dialog-region"></div>

<script id="section-list-item" type="text/template">
  <div class="add-card"></div>
  <div class="title">
    <h1 class="text-center">{{= title }}</h1>
  </div>

  <div class="cards-region"></div>
</script>

<script id="card-new" type="text/template">
  <a href="" title="Add Card">
    <div class="fa fa-plus js-card-new"></div>
  </a>
</script>

<script id="card-list" type="text/template">
  <div class="card-stack"></div>
</script>

<script id="card-list-item" type="text/template">
  <div class="data text-justify">
    <div class="text">
      {{= title }}
    </div>
    <!--div class="tags">
      Lorem ipsum
    </div-->
  </div>
  <div class="card-panel">
    <div class="assignee-btn">
      <div class="vertical-center">
      </div>
    </div>
    <a href="" title="Edit or Delete Card">
      <div class="edit-delete-btn">
        <div class="text-center vertical-center js-card-edit">
          <span class="fa fa-edit"></span>
        </div>
      </div>
    </a>
  </div>
</script>

<script id="card-form" type="text/template">
  <form>
    {{ if (section !== undefined) { }}
      <input id="card-section" name="section" type="hidden"
        value="{{= section }}" />
    {{ } }}

    <div class="control-group">
      <label for="card-title" class="control-label">
        Title:</label>
      <input id="card-title" name="title" type="text"
        value="{{= title }}" class="form-control" />
    </div>

    <button class="btn js-card-submit">Save</button>
  </form>
</script>

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cards</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.title %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @card.title %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-US">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Kanban Board</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>

  <%= javascript_include_tag 'application' %>
</body>
</html>